# Spring Boot Packager
# (implemented by Salesforce)

# Even though there are no build steps for this Bazel package (just static files here),
# we need this BUILD file here to make it an addressable Bazel package.

# Example (for BUILD files):
#   load("//tools/springboot:springboot.bzl", "springboot")

# See the springboot.bzl file for detailed usage instructions.

exports_files(["springboot.bzl", "springboot_pkg.sh"])
