#
# Copyright (c) 2017-2021, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root  or https://opensource.org/licenses/BSD-3-Clause
#

# List of standard imports bundles that tend to be used together in Spring Boot.
# Please create/curate new bundles and contribute back to the community. Thanks!

java_import(
    name = "springboot_required_deps",
    jars = [],
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:org_springframework_boot_spring_boot",
        "@maven//:org_springframework_boot_spring_boot_actuator",
        "@maven//:org_springframework_boot_spring_boot_actuator_autoconfigure",
        "@maven//:org_springframework_boot_spring_boot_autoconfigure",
        "@maven//:org_springframework_boot_spring_boot_loader",
        "@maven//:org_springframework_boot_spring_boot_starter",
        "@maven//:org_springframework_boot_spring_boot_starter_logging",
    ],
)

java_import(
    name = "springboot_jetty_starter_deps",
    jars = [],
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:org_springframework_boot_spring_boot_starter_jetty",
    ],
)

java_import(
    name = "springboot_web_starter_deps",
    jars = [],
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:org_springframework_boot_spring_boot_starter_web",
        "@maven//:org_springframework_spring_webmvc",
    ],
)

java_import(
    name = "springboot_logging_deps",
    jars = [],
    visibility = ["//visibility:public"],
    exports = [
    ],
)

java_import(
    name = "springboot_jackson_deps",
    jars = [],
    visibility = ["//visibility:public"],
    exports = [
    ],
)
