#
# Copyright (c) 2017-2021, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root  or https://opensource.org/licenses/BSD-3-Clause
#

#
# SAMPLE LIST OF DEPENDENCIES
# You will need to curate this list as your project requires it.
# During migration, you can use the 'mvn dependency:list' command to help you.
#
# UPDATING THIS LIST
# After updating the list below, you need to regenerate the pinned target list:
#  bazel run @unpinned_maven//:pin

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

repositories = [
    "https://repo1.maven.org/maven2",
]

def external_maven_jars():
    maven_install(
        artifacts = [
            "aopalliance:aopalliance:1.0",
            "ch.qos.logback:logback-classic:1.2.3",
            "ch.qos.logback:logback-core:1.2.3",
            "com.fasterxml.jackson.core:jackson-annotations:2.10.0",
            "com.fasterxml.jackson.core:jackson-core:2.10.0",
            "com.fasterxml.jackson.core:jackson-databind:2.10.0",
            "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.10.0",
            "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.10.0",
            "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.10.0",
            "com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.10.0",
            "com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.10.0",
            "com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.10.0",
            "com.fasterxml.jackson.module:jackson-module-parameter-names:2.10.0",
            "com.fasterxml.jackson.module:jackson-module-paranamer:2.10.0",
            "com.fasterxml.jackson.module:jackson-module-scala_2.11:2.10.0",
            "com.fasterxml:classmate:1.5.1",
            "com.github.ben-manes.caffeine:caffeine:2.8.0",
            "com.github.zafarkhaja:java-semver:0.9.0",
            "com.google.code.gson:gson:2.8.6",
            "com.google.guava:guava:26.0-jre",
            "com.google.inject:guice:4.0",
            "commons-beanutils:commons-beanutils:1.9.4",
            "commons-codec:commons-codec:1.13",
            "commons-collections:commons-collections:3.2.2",
            "commons-httpclient:commons-httpclient:3.1",
            "commons-io:commons-io:2.6",
            "commons-lang:commons-lang:2.6",
            "commons-logging:commons-logging:1.2",
            "io.dropwizard.metrics:metrics-core:4.1.1",
            "io.netty:netty:3.10.1.Final",
            "io.netty:netty-buffer:4.1.43.Final",
            "io.netty:netty-codec:4.1.43.Final",
            "io.netty:netty-codec-http:4.1.43.Final",
            "io.netty:netty-codec-http2:4.1.43.Final",
            "io.netty:netty-codec-socks:4.1.43.Final",
            "io.netty:netty-common:4.1.43.Final",
            "io.netty:netty-handler:4.1.43.Final",
            "io.netty:netty-handler-proxy:4.1.43.Final",
            "io.netty:netty-resolver:4.1.43.Final",
            "io.netty:netty-transport:4.1.43.Final",
            "io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.43.Final",
            "javax.annotation:javax.annotation-api:1.3.2",
            "javax.inject:javax.inject:1",
            "javax.servlet:javax.servlet-api:4.0.1",
            "javax.validation:validation-api:2.0.1.Final",
            "javax.ws.rs:javax.ws.rs-api:2.1",
            "jline:jline:0.9.94",
            "log4j:log4j:1.2.17",
            "net.bytebuddy:byte-buddy:1.10.2",
            "net.sourceforge.findbugs:annotations:1.2.0",
            "org.apache.commons:commons-lang3:3.9",
            "org.apache.httpcomponents:httpclient:4.5.10",
            "org.apache.httpcomponents:httpcore:4.4.12",
            "org.apache.logging.log4j:log4j-api:2.12.1",
            "org.apache.logging.log4j:log4j-to-slf4j:2.12.1",
            "org.aspectj:aspectjrt:1.9.4",
            "org.aspectj:aspectjweaver:1.9.4",
            "org.codehaus.jackson:jackson-core-asl:1.9.13",
            "org.codehaus.jackson:jackson-mapper-asl:1.9.13",
            "org.codehaus.janino:commons-compiler:2.7.8",
            "org.codehaus.janino:janino:2.7.8",
            "org.eclipse.jetty.websocket:javax-websocket-client-impl:9.4.22.v20191022",
            "org.eclipse.jetty.websocket:javax-websocket-server-impl:9.4.22.v20191022",
            "org.eclipse.jetty.websocket:websocket-api:9.4.22.v20191022",
            "org.eclipse.jetty.websocket:websocket-client:9.4.22.v20191022",
            "org.eclipse.jetty.websocket:websocket-common:9.4.22.v20191022",
            "org.eclipse.jetty.websocket:websocket-server:9.4.22.v20191022",
            "org.eclipse.jetty.websocket:websocket-servlet:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-annotations:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-client:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-continuation:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-http:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-io:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-plus:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-rewrite:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-security:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-server:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-servlet:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-servlets:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-util:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-webapp:9.4.22.v20191022",
            "org.eclipse.jetty:jetty-xml:9.4.22.v20191022",
            "org.freemarker:freemarker:2.3.29",
            "org.glassfish.hk2.external:aopalliance-repackaged:2.5.0-b42",
            "org.glassfish.hk2.external:javax.inject:2.5.0-b42",
            "org.glassfish.hk2:class-model:2.5.0-b42",
            "org.glassfish.hk2:config-types:2.5.0-b42",
            "org.glassfish.hk2:hk2:2.5.0-b42",
            "org.glassfish.hk2:hk2-api:2.5.0-b42",
            "org.glassfish.hk2:hk2-config:2.5.0-b42",
            "org.glassfish.hk2:hk2-core:2.5.0-b42",
            "org.glassfish.hk2:hk2-locator:2.5.0-b42",
            "org.glassfish.hk2:hk2-runlevel:2.5.0-b42",
            "org.glassfish.hk2:hk2-utils:2.5.0-b42",
            "org.glassfish.hk2:osgi-resource-locator:1.0.3",
            "org.glassfish.hk2:spring-bridge:2.5.0-b42",
            "org.glassfish.jersey.containers:jersey-container-servlet:2.29.1",
            "org.glassfish.jersey.containers:jersey-container-servlet-core:2.29.1",
            "org.glassfish.jersey.core:jersey-client:2.29.1",
            "org.glassfish.jersey.core:jersey-common:2.29.1",
            "org.glassfish.jersey.core:jersey-server:2.29.1",
            "org.glassfish.jersey.ext:jersey-entity-filtering:2.29.1",
            "org.glassfish.jersey.media:jersey-media-jaxb:2.29.1",
            "org.glassfish.jersey.media:jersey-media-json-jackson:2.29.1",
            "org.hdrhistogram:HdrHistogram:2.1.11",
            "org.hibernate:hibernate-validator:5.4.3.Final",
            "org.javassist:javassist:3.24.0-GA",
            "org.jboss.logging:jboss-logging:3.4.1.Final",
            "org.jvnet:tiger-types:1.4",
            "org.mortbay.jasper:apache-el:8.5.40",
            "org.mpierce.metrics.reservoir:hdrhistogram-metrics-reservoir:1.1.0",
            "org.objenesis:objenesis:3.0.1",
            "org.ow2.asm:asm:7.1",
            "org.ow2.asm:asm-commons:7.1",
            "org.ow2.asm:asm-tree:7.1",
            "org.slf4j:jcl-over-slf4j:1.7.26",
            "org.slf4j:jul-to-slf4j:1.7.26",
            "org.slf4j:log4j-over-slf4j:1.7.26",
            "org.slf4j:slf4j-api:1.7.26",
            "org.springframework.boot:spring-boot:2.2.1.RELEASE",
            "org.springframework.boot:spring-boot-actuator:2.2.1.RELEASE",
            "org.springframework.boot:spring-boot-actuator-autoconfigure:2.2.1.RELEASE",
            "org.springframework.boot:spring-boot-autoconfigure:2.2.1.RELEASE",
            "org.springframework.boot:spring-boot-configuration-processor:2.2.1.RELEASE",
            "org.springframework.boot:spring-boot-loader:2.1.4.RELEASE",
            "org.springframework.boot:spring-boot-starter:2.2.1.RELEASE",
            "org.springframework.boot:spring-boot-starter-actuator:2.1.4.RELEASE",
            "org.springframework.boot:spring-boot-starter-freemarker:2.1.4.RELEASE",
            "org.springframework.boot:spring-boot-starter-jdbc:2.1.4.RELEASE",
            "org.springframework.boot:spring-boot-starter-jetty:2.1.4.RELEASE",
            "org.springframework.boot:spring-boot-starter-logging:2.2.1.RELEASE",
            "org.springframework.boot:spring-boot-starter-security:2.1.4.RELEASE",
            "org.springframework.boot:spring-boot-starter-test:2.1.4.RELEASE",
            "org.springframework.boot:spring-boot-starter-web:2.1.4.RELEASE",
            "org.springframework.boot:spring-boot-test:2.2.1.RELEASE",
            "org.springframework.boot:spring-boot-test-autoconfigure:2.2.1.RELEASE",
            "org.springframework.boot:spring-boot-starter-thymeleaf:2.1.4.RELEASE",
            "org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE",
            "org.springframework.plugin:spring-plugin-metadata:jar:1.2.0.RELEASE",
            "org.springframework.retry:spring-retry:1.2.4.RELEASE",
            "org.springframework.security:spring-security-config:5.2.1.RELEASE",
            "org.springframework.security:spring-security-core:5.2.1.RELEASE",
            "org.springframework.security:spring-security-web:5.2.1.RELEASE",
            "org.springframework:spring-aop:5.2.1.RELEASE",
            "org.springframework:spring-aspects:5.1.6.RELEASE",
            "org.springframework:spring-beans:5.2.1.RELEASE",
            "org.springframework:spring-context:5.2.1.RELEASE",
            "org.springframework:spring-context-support:5.2.1.RELEASE",
            "org.springframework:spring-core:5.2.1.RELEASE",
            "org.springframework:spring-expression:5.2.1.RELEASE",
            "org.springframework:spring-jdbc:5.2.1.RELEASE",
            "org.springframework:spring-test:5.2.1.RELEASE",
            "org.springframework:spring-tx:5.2.1.RELEASE",
            "org.springframework:spring-web:5.2.1.RELEASE",
            "org.springframework:spring-webmvc:5.2.1.RELEASE",
            "org.yaml:snakeyaml:1.25",
        ],
        excluded_artifacts = [
            "org.springframework.boot:spring-boot-starter-tomcat",
        ],
        repositories = repositories,
        fetch_sources = True,
        version_conflict_policy = "pinned",
        strict_visibility = True,
        generate_compat_repositories = False,
        # comment the following line in once maven_install.json generation doesn't include user id
        maven_install_json = "@bazel_springboot_rule//:maven_install.json",
        resolve_timeout = 1800,
    )
