#!/bin/bash
#
# Copyright (c) 2021, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root  or https://opensource.org/licenses/BSD-3-Clause
#

# This file is used to generate the environment variables used by the
# default_bazelrun_script.sh for launching Spring Boot applications with
# bazel run, as in 'bazel run //examples/helloworld'

set -e

rulename=${1}
outputfile=${2}

echo "Invoked bazelrun_stop_gen on target ${rulename} as ${outputfile}"

echo "#!/bin/bash" > ${outputfile}
echo "" > ${outputfile}
echo "# This file was generated by the springboot rule. It is provided as a way to" > ${outputfile}
echo "# stop a running springboot application that was started using 'bazel run'" > ${outputfile}
echo "# with the bazelrun_background option set to True." > ${outputfile}
echo "" > ${outputfile}

echo "# Applications started in this way will write the process id to /tmp/${rulename}.pid" > ${outputfile}
echo "" > ${outputfile}

echo "pidfile=/tmp/${rulename}.pid" >> ${outputfile}
echo "pid=\`cat \$pidfile\`" >> ${outputfile}
echo "echo \"bazelrun_stop: killing the running process \$pid...\"" >> ${outputfile}
echo "kill -9 \$pid" >> ${outputfile}
echo "if [ \$? -eq 0 ]; then" >> ${outputfile}
echo "  echo \"bazelrun_stop: process \$pid terminated.\"" >> ${outputfile}
echo "fi" >> ${outputfile}
