
exports_files([
    "springbootjar.bzl",
    "springboot_pkg.py",
])


py_binary(
    name = "springboot_pkg",
    srcs = [
        "springboot_pkg.py",
    ],
    visibility = ["//visibility:public"],
)
